// Room
export const FETCH_ROOMS = 'FETCH_ROOMS';
export const FETCH_ROOMS_FAILED = 'FETCH_ROOMS_FAILED';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';

// User
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';


// Friend
export const FETCH_FRIEND = 'FETCH_FRIEND';
export const FETCH_FRIEND_FAILED = 'FETCH_FRIEND_FAILED';
export const FETCH_FRIEND_SUCCESS = 'FETCH_FRIEND_SUCCESS';

// Friend
export const FETCH_ROOM_TABS = 'FETCH_ROOM_TABS';
export const FETCH_ROOM_TABS_FAILED = 'FETCH_ROOM_TABS_FAILED';
export const FETCH_ROOM_TABS_SUCCESS = 'FETCH_ROOM_TABS_SUCCESS';

export const OPEN_MODAL = 'OPEN_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const OPENED_MODAL = 'OPENED_MODAL'
export const HIDED_MODAL = 'HIDED_MODAL'

// MODAL NAMES
export const MORE_MENU_POPUP = 'MORE_MENU_POPUP'
export const MOBILE_FRIEND_LIST = 'MOBILE_FRIEND_LIST'
export const NOTIFICATION = 'NOTIFICATION'
export const CHANGE_AVATAR = 'CHANGE_AVATAR'
export const SEND_GIFT = 'SEND_GIFT'
export const UPGRADE_MEMBERSHIP = 'UPGRADE_MEMBERSHIP'
export const SAY_THANKS = 'SAY_THANKS'
export const PURCHASE = 'PURCHASE'
export const RECEIVE_UPGRADE = 'RECEIVE_UPGRADE'
export const BAN_WINDOW = 'BAN_WINDOW'
export const MUTE_WINDOW = 'MUTE_WINDOW'
export const MUTE_SYSTEM = 'MUTE_SYSTEM'
export const KICK_WINDOW = 'KICK_WINDOW'
export const KICK_SYSTEM = 'KICK_SYSTEM'
export const BAN_MANAGEMENT = 'BAN_MANAGEMENT'
export const USER_REPORTED = 'USER_REPORTED'
export const SETTING_BOX = 'SETTING_BOX'
export const IGNORE_LIST = 'IGNORE_LIST'
export const CREATE_GROUP = 'CREATE_GROUP'
export const SEC_SYS_SETTING = 'SEC_SYS_SETTING'
export const EXCEED_LIMIT = 'EXCEED_LIMIT'
export const SEC_WAIT_SYSTEM = 'SEC_WAIT_SYSTEM'
export const SEND_ANNOUNCEMENT = 'SEND_ANNOUNCEMENT'
export const ANNOUNCEMENT_MSG = 'ANNOUNCEMENT_MSG'
export const FRIEND_REQUEST = 'FRIEND_REQUEST'
export const CAMERA_MIC = 'CAMERA_MIC'
export const COUNTRY_BAN = 'COUNTRY_BAN'
export const BANNED_SYS_MSG = 'BANNED_SYS_MSG'
export const PRIVATE_MSG_REQ = 'PRIVATE_MSG_REQ'
export const MY_ACCOUNT = 'MY_ACCOUNT'
export const NOTICE = 'NOTICE'
export const VIRTUAL_CURRENCY_SHOP = 'VIRTUAL_CURRENCY_SHOP'
export const OPEN_CHAT = 'OPEN_CHAT'
export const VIDEO_BOX1 = 'VIDEO_BOX1'
export const VIDEO_BOX = 'VIDEO_BOX'
export const PRIVATE_CHAT = 'PRIVATE_CHAT'
export const GROUP_CONVERSATION = 'GROUP_CONVERSATION'
export const GROUP_CONVERSATION_FULL = 'GROUP_CONVERSATION_FULL'
export const UPGRADE_ROOM = 'UPGRADE_ROOM'
export const DELETE = 'DELETE'
export const REPORT = 'REPORT'
export const EXIT = 'EXIT'
export const CHANGE_GROUP_NAME = 'CHANGE_GROUP_NAME'
export const LOG_OUT = 'LOG_OUT'
export const ABOUT_APP = 'ABOUT_APP'
export const TERMS_AND_CONDITION = 'TERMS_AND_CONDITION'
export const CONTACT_US = 'CONTACT_US'
export const HELP = 'HELP'
export const OPEN_CHAT_MENU = 'OPEN_CHAT_MENU'
