export const Users = [
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level3',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Video Call',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level2',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Speak',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'User-Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise Hand',
        gender: 'Men',
        userStatus: 'online',
    }
]