export const Users = [
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Women',
        status: 'away',
    },
    {
        userID: '',
        name: 'aasddb',
        userAvatar: '',
        userLevel: 'Level3',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Video-Call',
        gender: 'Men',
        status: 'away',
    },
    {
        userID: '',
        name: 'adasdb',
        userAvatar: '',
        userLevel: 'Level2',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Speak',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'FH',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'MeSDFGn',
        status: 'offline',
    },
    {
        userID: '',
        name: 'adadfasdb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'addfadfb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Voice-call',
        gender: 'Women',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'offline',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Voice-call',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Voice-call',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Speak',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    },
    {
        userID: '',
        name: 'adb',
        userAvatar: '',
        userLevel: 'Level1',
        userLevelImg: '',
        ActionImg: '',
        actionTitle: 'Raise-Hand',
        gender: 'Men',
        status: 'status',
    }
]